### PR TITLE
Remove postgres in espresso e2e test

### PR DESCRIPTION
**Pull request by ImJeremyHe**
Since this PR https://github.com/EspressoSystems/espresso-sequencer/pull/1707 has been merged and the `espresso-dev-node` doesn't require us to run a `postgres` anymore, so we can remove relevant config and make it cleaner.
And we also added a dev-node port for debugging according to https://github.com/EspressoSystems/espresso-sequencer/pull/1709

### CODE REVIEW

**Review by Sneh1999 — APPROVED** [review]
Code LGTM! I think for my own understanding - you mentioned that dev node doesnt require postgres but isnt it running a script [here](https://github.com/EspressoSystems/espresso-sequencer/blob/228d003dccf3ead64b30caa8b7eae0e994ecbaee/docker/espresso-dev-node.Dockerfile#L20)?

**Comment by zacshowa** [comment]
I would like to expand on Sneh's comment and check my own understanding of docker. 

It seems as if postgres was recently added into the launch script for the dev node. Further, the env variables used for configuration would have been coming from the .env and docker-compose file in this repo. From my current understanding, this would imply that the `espresso-dev-node` dockerfile would be looking for these env vars, not finding them, and then failing to start postgres. 

If this isn't the case, is postgres use being handled entirely within the espresso-sequencer repo now? Does omitting the postgres setup information simply mean that somehwere in the pipeline we decide to not start postgres gracefully? If so where does that occur?

**Review by zacshowa — APPROVED** [review]
I left one comment to further my understanding of the lifecycle of building the docker image related to these changes. Other than that LGTM :ship:

**Comment by ImJeremyHe** [comment]
Currently `postgres` is a necessity for running the `espresso builder`. But for the developers using the dev node, they should not pay any attention to the internal issue. So we integrated the `postgres` into the image and as what @Sneh1999 said, we use a shell script to run the `postgres` inside the Docker image. `postgres` is still being used in the `espresso-dev-node`, but we don't have to ask the users/developers to run a `postgres` anymore, which may be confusing to them.

@zacshowa I think you can get the answer from [this script](https://github.com/EspressoSystems/espresso-sequencer/blob/main/scripts/launch-dev-node-with-postgres). This script will be copied to the image. The entry of `espresso-dev-node` image is this script and you can see this script will set the envs and run the postgres before startting the binary.

**Pull request merged**
