### PR TITLE
Clean up

### LINKED ISSUE #346: Cleanup logs
Currently we have a lot of unnecessary logs in our batch poster, we should clean them up, as much as possible

### PR DESCRIPTION
**Pull request by ImJeremyHe**
Closes #346 

### This PR:
Cleans the logs by utilizing the ephemeral error handler

### This PR does not:
change any logic

### CODE REVIEW

**Review by zacshowa — APPROVED** [review]
LGTM

**Review by Sneh1999 — COMMENTED** [review]
@ImJeremyHe if possible can we also delete some logs like I know I added a log to print attestation quote, we can delete that, I dont think thats needed. 

I also see this error popping up:
``
ERROR[11-24|23:27:54.912] error checking escape hatch              err="request failed with status 404 and body
```
I think this should be a warning because we retry so maybe we can change this to a warning and it then becomes `WARN: error checking escape hatch, will retry`

Another Info log which is not valid anymore:
```
INFO [11-24|23:27:53.652] submitting transaction to espresso using sovereign sequencer
```

This should now be
```
INFO [11-24|23:27:53.652] submitting transaction to hotshot for finalization
```

**Comment by ImJeremyHe** [comment]
> Remove the GetArbOSConfigAtHeight  from execution/gethexec/node.go and execution/gethexec/executionengine.go

Does that mean we don't need this anymore? As soon as we start the new batch poster, then the migration has been finished?

**Comment by Sneh1999** [comment]
> > Remove the GetArbOSConfigAtHeight  from execution/gethexec/node.go and execution/gethexec/executionengine.go
> 
> Does that mean we don't need this anymore? As soon as we start the new batch poster, then the migration has been finished?

You are right, I forgot we are using this in the batch poster. We should not delete this, thank you!

**Review by Sneh1999 — APPROVED** [review]
Thanks @ImJeremyHe, this looks good 🎉

**Pull request merged**
